version: '3'
services:
  redis:
    container_name: go-redis
    image: redis:5.0.7
    command: redis-server
    volumes:
      - redis-volume:/data
    ports:
      - "6379:6379"
  # jwt:
  #   container_name: auth-service
  #   image: auth-service
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - db
  #     - redis
  db:
    image: postgres:14.0-alpine
    container_name: postgres-go
    env_file:
      - './dotenv/.postgres.env'
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  redis-volume:
  pg-data: